### ISSUE TITLE
Can't find in accessories

### ISSUE THREAD

**Issue by Cliff2103** [jochem725/homebridge-toon#1]
Should this plugin still work? I can't find it in accessories.

**Comment by jochem725** [comment]
@Cliff2103 It should still be working, except for setting the temperature. Are you sure you've correctly added the plugin to the `config.json` file of homebridge?

**Comment by Cliff2103** [comment]
Yes, I added the config.json exactly as described. I see the homebridge in the homekit app but this plugin doesn't show as accessory maybe I can try another device tonight.

**Comment by jochem725** [comment]
@Cliff2103 Can you post your config, so I can check if the issue is in your config or in the plugin?

**Comment by Cliff2103** [comment]
`{ "accessories": [
    {
      "accessory": "Toon",
      "name": "Thermostaat",
      "username": "Cliff2103",
      "password": "XXXXXX"
    }
  ]
}
`

**Comment by jochem725** [comment]
@Cliff2103 I think my configuration description may be a bit confusing. I've prepared a configuration file you can try. https://gist.github.com/jochem725/b74bab24b5ec05b2496fb2d7f8daeadb

If this configuration does not run, please post the log Homebridge gives on startup.

**Comment by Cliff2103** [comment]
[2016-06-25 16:02:29] Loaded plugin: homebridge-toon
[2016-06-25 16:02:29] Registering accessory 'homebridge-toon.Toon'
[2016-06-25 16:02:29] ---
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

```
┌────────────┐     
│ 031-45-154 │     
└────────────┘     
```

[2016-06-25 16:02:29] Homebridge is running on port 51826.

It does run and show this, but I can't find it in the homekit app.

**Comment by Cliff2103** [comment]
[2016-06-25 16:31:12] Loaded plugin: homebridge-toon
[2016-06-25 16:31:12] Registering accessory 'homebridge-toon.Toon'
[2016-06-25 16:31:12] ---
[2016-06-25 16:31:12] Loaded config.json with 1 accessories and 0 platforms.
[2016-06-25 16:31:12] ---
[2016-06-25 16:31:12] Loading 1 accessories...
[2016-06-25 16:31:12] [Toon Thermostaat] Initializing Toon accessory...
[2016-06-25 16:31:12] [Toon Thermostaat] Toon Initialized, it may take a few minutes before any data will be visible to HomeKit.
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

```
┌────────────┐     
│ 031-45-154 │     
└────────────┘     
```

[2016-06-25 16:31:12] Homebridge is running on port 51826.
[2016-06-25 16:31:13] [Toon Thermostaat] Succesfully logged in to Toon.

Now I have this, so I guess I fixed the plug-in. I still can't find it in homekit but I guess that has to do with something else.

**Comment by jochem725** [comment]
@Cliff2103 In the first output you gave, the `config.json` was not loaded. The output you just posted should be correct 😄. I'm not sure why it does not show up in HomeKit though, which app do you use?

**Comment by Cliff2103** [comment]
It works now after a reboot. Thanks a lot for your support :)
Can I support you with the bug for setting the temperature?

**Comment by jochem725** [comment]
@Cliff2103 No problem, glad to see this fixed. I believe the temperature issue has something to do with the API itself. It appears to be working now, while it didn't work a few days ago. Let me know if you experience the problem, so I can look into it :)
