### ISSUE TITLE
Toon and Boxx

### ISSUE THREAD

**Issue by hyperbart** [jochem725/homebridge-toon#11]
The Toon by Eneco in Netherlands is also available in Belgium as the Boxx by Engie (Engie/Electrabel is like Eneco)

It's completely the same hardware but maybe the "branded" backend for the energy supplier is different. I tried entering my credentials for Boxx but got authenticating errors. Any chance you could make this compatible with Boxx?

**Comment by jochem725** [comment]
@hyperbart It is true that the plugin does not work with the Belgian version of Toon. This plugin uses Toon op Afstand (https://toonopafstand.eneco.nl), a web based application by Eneco to get the required data. If Boxx also has a web based application it should be easy to make the plugin compatible with Boxx, but the only thing I've found so far is a native application.

**Comment by ethempekin** [comment]
I guess there is no update on this issue.
