### ISSUE TITLE
No debug

### ISSUE THREAD

**Issue by gielk** [jochem725/homebridge-toon#12]
Ik krijg een error bij het laden van de Toon plugin.

![image](https://cloud.githubusercontent.com/assets/24224715/24081455/493af406-0cb4-11e7-8cae-10a4d0bc2652.png)

tijdens installeren kwam deze melding al.
![image](https://cloud.githubusercontent.com/assets/24224715/24081486/fe70f44c-0cb4-11e7-9d97-bf07ab68be2e.png)

**Comment by jochem725** [comment]
@gielk Ik vermoed dat dit te maken heeft met het niet global installeren van de plugin.
Dit zou moeten werken, `npm install -g homebridge-toon`

**Comment by gielk** [comment]
oooooh !! daarom is die -g dus
bedankt nu weet ik ook hoe ik dit in vervolg kan oplossen ik zat telkens alles te kopieren !!

super bedankt !!
