### ISSUE TITLE
Gaat dit voor zorgen dat het niet meer gaat werken

### ISSUE THREAD

**Issue by gielk** [jochem725/homebridge-toon#14]
De website van toonopafstand is verdwenen. Deze is weg werkt het nog wel en blijft het nog wel werken ?

![img_5346](https://user-images.githubusercontent.com/24224715/28372553-51f62e70-6ca0-11e7-9ad3-b061b9d07340.PNG)

**Comment by jochem725** [comment]
@gielk Voorlopig is de API nog online, en kan er dus nog data worden opgehaald. Als Eneco besluit ook de API af te sluiten, dan stopt de plugin met werken.
