### ISSUE TITLE
Siri kan geen temp opvragen

### ISSUE THREAD

**Issue by DennisDeKoster** [jochem725/homebridge-toon#15]
Zojuist geinstalleerd en werkt super! Erg blij mee.
Echter alleen als ik Siri vraag hoe warm het thuis/in de kamer/in de "woonkamer" is, kan ze geen antwoord geven (geen response)
. 
Ik ben vrij newbie met raspberry pi, maar als ik nog iets qua info moet opzoeken en posten, hoor ik graag hoe :)

-raspbian stretch: Linux raspberrypi 4.9.54-v7+ #1042 SMP Wed Oct 11 23:18:56 BST 2017 armv7l GNU/Linux
-homebridge: v0.4.28
-nodejs: v8.x
-iphone: iOS 11.0.2
-ipad: iOS 10.3.3

**Comment by jochem725** [comment]
@DennisDeKoster Fijn dat je er blij mee bent 😄
Na wat testen lijkt het erop dat ik zelf ook de temperatuur niet meer kan opvragen bij Siri.
Ik ga kijken wat ik kan doen.

**Comment by jochem725** [comment]
@DennisDeKoster Ik heb het probleem opgelost en de hele plugin herschreven zodat hij beter zou moeten werken. Ik heb een test geupload naar npm die je kunt installeren via 

`npm install -g homebridge-toon@ts-test`.

 Er is een wijziging in de `config.json`, de config staat nu niet meer onder `accessories` maar onder `platforms`. Ik ben benieuwd of het een beetje werkt 🔥.

**Comment by DennisDeKoster** [comment]
Super! Ik ga het proberen en ik laat het weten hoe het gaat. Tot nu toe werkt alles fantastisch (sinds kort ook een Apple Watch). 

Thanks voor de snelle support!

**Comment by DennisDeKoster** [comment]
Oh nee, Siri kan wel halve graden instellen. Maar wordt misschien een rommeltje in de home app 😊

**Comment by DennisDeKoster** [comment]
Zojuist geïnstalleerd en getest, alles lijkt prima te werken! Ook Siri reageert snel en correct. 

Ik zie wel mijn adresgegevens voorbij komen. Ik weet niet in hoeverre deze info binnen huiselijke kringen blijft? 

Ook leuk dat nu merk, type en serienummer correct weergegeven worden in de Home app. 

Kan ik de oude uninstallen, of krijgt die een update en moet de beta uiteindelijk er weer af?
Erg bedankt in ieder geval!

**Comment by jochem725** [comment]
@DennisDeKoster Mooi! Wat betreft adresgegevens, de plugin logt in, ontvangt deze gegevens en geeft ze weer. De reden dat ze weergegeven worden is dat er soms meerdere adressen per account zijn. Als dat het geval is, moet je kiezen. 

Als het goed is heeft deze versie de oude versie overschreven.

**Comment by DennisDeKoster** [comment]
Nou qua functionaliteit nog geen problemen ondervonden. Wel is de homebridge-toon vannacht erg druk geweest volgens de log. Ik zie twee soorten errors voorbijkomen. Om de paar minuten zo’n beetje. 
Misschien heb je hier wat aan mocht je het nog verder willen perfectioneren.  

```
Oct 25 02:56:05 raspberrypi homebridge[347]: [2017-10-25 02:56:05] [thermostaat] 
TypeError: Cannot read property 'success' of undefined
```
```
Oct 25 02:57:23 raspberrypi homebridge[347]: [2017-10-25 02:57:23] [thermostaat] 
{ RequestError: Error: getaddrinfo EAI_AGAIN toonopafstand.eneco.nl:443
```

**Comment by DennisDeKoster** [comment]
Hoi Jochem, als ‘jouw beta tester’ heb ik toch nog wat gevonden :D. 

De huidige temp en ingestelde temp werd dit niet ge-update naar homebridge. Deze blijft de laatst bekende waarde weergeven. De temp instellen met homebridge lukt wel gewoon. 

Na een reboot kreeg ik alleen maar errors en geen verbinding meer, dus nu draait de ‘gewone’ versie weer en Siri doet het nu wel volledig. Geen idee hoe... Maar deze versie (accessory ipv platform) draait duidelijk stabieler.

Groetjes, Dennis

**Comment by jochem725** [comment]
@DennisDeKoster Een paar errors worden niet correct opgevangen, daarom worden ze gelogd. Ga ik naar kijken. Als je de temperatuur update op de Toon kan het even duren voor die in de app staat, dit komt omdat de temperatuur (vreemd genoeg) niet altijd wordt meegestuurd door Toon op afstand. 

Het kan zijn dat er na een reboot teveel sessies actief zijn, waardoor een nieuwe sessie wordt geweigerd. 

Ik ga ermee aan de slag 😄

**Comment by jochem725** [comment]
@DennisDeKoster Ik heb een probleem opgelost waarbij er maar één keer om een update gevraagd werd van de Toon gegevens, vandaar dat er niet al te veel gebeurde 😅. Ook zou het aantal error logs nu een stuk lager moeten zijn. Kun je het nog eens proberen via

`npm install -g homebridge-toon@ts-test`

**Comment by DennisDeKoster** [comment]
@jochem725 😂Kan gebeuren. Dan ga ik vanavond weer even installeren. Leuk dat je er steeds zo snel mee aan de slag gaat. Erg bedankt weer!

**Comment by frankveldink** [comment]
@jochem725 Top gedaan. Hierbij kan ik ook bevestigen dat het werkt.

**Comment by posttoast** [comment]
Hier ook een tevreden (nieuwe) gebruiker. Ik heb hier vandaag de master-branch geïnstalleerd om daarna te zien dat je hem herschreven hebt. Ik zie dat je een pull request open hebt staan van je test-branch naar de master. Is het de bedoeling dat die op korte termijn naar master gaat? Zo ja, dan ga ik nu de testversie niet installeren en wacht ik daarop :)
