### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by WimBre** [jochem725/homebridge-toon#17]
Hi Jochem,

I have changed my config.json file and now receiving undermentioned error.

2017-11-14 18:59:08] [TOON] Authenticating...
(node:3174) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: There was an error authenticating with Toon.
undefined
(node:3174) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

What could be the cause?

**Comment by RienduPre** [comment]
Eneco has changed their authentication certificate, don't know if this can be sloved
