### ISSUE TITLE
Does Toon with Homebridge still work

### ISSUE THREAD

**Issue by jvdv23** [jochem725/homebridge-toon#18]
Hello.

I am trying to install it in Homebridge as mentioned below the video but without succes. Does it still work or am I doing something wrong?

**Comment by gielk** [comment]
Hello, for me it is still working !

<img width="439" alt="image" src="https://user-images.githubusercontent.com/24224715/41651499-00b6f3b6-7481-11e8-87e5-49c8a3e3ccd8.png">

<img width="439" alt="image" src="https://user-images.githubusercontent.com/24224715/41651533-115322d0-7481-11e8-957d-d7b6aa6f6f03.PNG">

**Comment by schweinefleish** [comment]
I installed it today and it still works

**Comment by rbeniers** [comment]
It is not working anymore....

I get the following error after adding Toon and the proper config to Homebridge;

Error: The requested platform 'Toon' was not registered by any plugin
