### ISSUE TITLE
Service Unavailable - not working

### ISSUE THREAD

**Issue by gielk** [jochem725/homebridge-toon#20]
Krijg de volgende error te zien. Het lijkt er op dat de website niet meer beschikbaar is om te gebruiken. Is er een oplossing mogelijk ?

[2019-2-12 15:38:47] [Toon] Retrieving client data from Toon op Afstand...
[2019-2-12 15:38:47] [Toon] Error: There was an error retrieving the client data from Toon.
"<html><body><h1>503 Service Unavailable</h1>\nNo server is available to handle this request.\n</body></html>\n"
    at /usr/local/lib/node_modules/homebridge-toon/toon.js:113:23
    at tryCatcher (/usr/local/lib/node_modules/homebridge-toon/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-toon/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-toon/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-toon/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-toon/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/usr/local/lib/node_modules/homebridge-toon/node_modules/bluebird/js/release/promise.js:638:18)
    at Request._callback (/usr/local/lib/node_modules/homebridge-toon/node_modules/bluebird/js/release/nodeback.js:42:21)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-toon/node_modules/request/request.js:186:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-toon/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-toon/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)

**Comment by Dmuiselaar** [comment]
Hier ook, zelfde probleem :(

**Comment by gielk** [comment]
@jochem725 Is er een update? 
Kan dit opgelost worden? 
Ga je hier nog mee bezig? 
Kan ik niet beter mijn toon gaan rooten ?

**Comment by MikeFumbler** [comment]
Zelfde in mijn setup. Geen contact meer.
Inmiddels op het Eneco/Toon forum wat vragen gesteld.

Reactie van Folkert (moderator):

"Ik heb het nagevraagd en als antwoord gekregen dat de oude backend niet meer te gebruiken is, het advies is om de huidige Api backend te gebruiken, Apps zoals Olisto en Homey verbinden al met de huidige backend."

Even nagevraagd wat de andere API Backend inhoudt en wat de reden en achterliggende gedachte is waarom de oude backend niet meer te gebruiken is.

**Comment by gielk** [comment]
> Zelfde in mijn setup. Geen contact meer.
> Inmiddels op het Eneco/Toon forum wat vragen gesteld.
> 
> Reactie van Folkert (moderator):
> 
> "Ik heb het nagevraagd en als antwoord gekregen dat de oude backend niet meer te gebruiken is, het advies is om de huidige Api backend te gebruiken, Apps zoals Olisto en Homey verbinden al met de huidige backend."
> 
> Even nagevraagd wat de andere API Backend inhoudt en wat de reden en achterliggende gedachte is waarom de oude backend niet meer te gebruiken is.

Top ben benieuwd of er een nieuwe versie komt, heb het idee dat @jochem725 niet echt meer met homebridge toon bezig is.

**Comment by MikeFumbler** [comment]
> > Zelfde in mijn setup. Geen contact meer.
> > Inmiddels op het Eneco/Toon forum wat vragen gesteld.
> > Reactie van Folkert (moderator):
> > "Ik heb het nagevraagd en als antwoord gekregen dat de oude backend niet meer te gebruiken is, het advies is om de huidige Api backend te gebruiken, Apps zoals Olisto en Homey verbinden al met de huidige backend."
> > Even nagevraagd wat de andere API Backend inhoudt en wat de reden en achterliggende gedachte is waarom de oude backend niet meer te gebruiken is.
> 
> Top ben benieuwd of er een nieuwe versie komt, heb het idee dat @jochem725 niet echt meer met homebridge toon bezig is.

We wachten af. Als er geen berichten komen, is de boel niet meer te gebruiken met deze Plug-in.
Ik ben benieuwd wat die andere API dan is, en hoe die is te benaderen. Helaas laten mijn programmeer skills het afweten om zelf iets te prutsen/aanpassen.

De optie rooten van de Toon module blijft dan open, wat ik overal lees. Nog geen idee wat dat allemaal voor een gevolgen heeft. En hoe dat in z'n werk gaat.

**Comment by jochem725** [comment]
@DylanNLD @MikeFumbler @gielk Het klopt dat de oude Toon API al een tijdje niet meer online is. De nieuwe backend waar Folkert naar verwijst is hier te vinden: https://developer.toon.eu.

Zelf gebruik ik de plugin al meer dan een jaar niet meer, vandaar dat ik de API change niet meer heb doorgevoerd. Ik zal in ieder geval een poging wagen om de plugin weer bruikbaar te maken :)

**Comment by MikeFumbler** [comment]
> @DylanNLD @MikeFumbler @gielk Het klopt dat de oude Toon API al een tijdje niet meer online is. De nieuwe backend waar Folkert naar verwijst is hier te vinden: https://developer.toon.eu.
> 
> Zelf gebruik ik de plugin al meer dan een jaar niet meer, vandaar dat ik de API change niet meer heb doorgevoerd. Ik zal in ieder geval een poging wagen om de plugin weer bruikbaar te maken :)

Geweldig! Dat is top.

Folkert schreef zojuist:
"...Er is een oude backend offline gehaald, wat ik begrepen heb is dat de functionaliteit ook via de api backend te realiseren moet zijn.
Of de huidige backend te integreren is met een HomeBridge Plug-in durf ik niet te zeggen, ik heb dit voor je uitgezet."

Tot gisteren toe werkte jouw Plugin voorbeeldig. Erg fijn die integratie (oa. via Eve). Ik hoop dat het je lukt om eea. weer werkende te krijgen.

Als ik je kan helpen met beta testen, let met know (R Pi3 B+)

**Comment by gielk** [comment]
> @DylanNLD @MikeFumbler @gielk Het klopt dat de oude Toon API al een tijdje niet meer online is. De nieuwe backend waar Folkert naar verwijst is hier te vinden: https://developer.toon.eu.
> 
> Zelf gebruik ik de plugin al meer dan een jaar niet meer, vandaar dat ik de API change niet meer heb doorgevoerd. Ik zal in ieder geval een poging wagen om de plugin weer bruikbaar te maken :)

Hier word ik blij van 😄 Net als @MikeFumbler zegt heb je hulp nodig hoor ik het wel top dat je nog wat tijd in wil steken ondangs dat je het niet meer gebruikt.

**Comment by gielk** [comment]
Heb net een beetje gekeken maar zijn echt ontzettend veel toffe dingen mogelijk met de nieuwe api. Ben benieuwd of je er uit komt.

**Comment by Dmuiselaar** [comment]
> > @DylanNLD @MikeFumbler @gielk Het klopt dat de oude Toon API al een tijdje niet meer online is. De nieuwe backend waar Folkert naar verwijst is hier te vinden: https://developer.toon.eu.
> > Zelf gebruik ik de plugin al meer dan een jaar niet meer, vandaar dat ik de API change niet meer heb doorgevoerd. Ik zal in ieder geval een poging wagen om de plugin weer bruikbaar te maken :)
> 
> Hier word ik blij van 😄 Net als @MikeFumbler zegt heb je hulp nodig hoor ik het wel top dat je nog wat tijd in wil steken ondangs dat je het niet meer gebruikt.

Zeker, echt super.
als er iets is waar ik mee kan helpen met testen? hoor ik t graag @jochem725 .

heb wel onderstaand kunnen vinden uit de magicmirror module (die bij mij ook niet werkt) maar wel al de API gebruikt.
// Private Properties
	var HOST = 'api.toonapi.com';
	var API = '/toon/api/v1/';
	var PORT = 443;

**Comment by gielk** [comment]
Is er al iets gelukt? Of heb je enig idee wanneer dit lukt? Mis mijn toon 😂

**Comment by RienduPre** [comment]
Me too...

**Comment by jochem725** [comment]
@gielk @DylanNLD Ik heb een testversie gemaakt met de nieuwe API en een aantal verbeteringen (zoals het niet meer tonen van COOL, HEAT, AUTO en OFF omdat Toon dit niet support.).

Je kunt hem hier installeren: `npm install -g homebridge-toon@beta`
Let op, de config.json moet worden aangepast:

```javascript
    {
      "platforms": [
        {
          "platform": "Toon",
          "name": "<NAME>",
          "username": "<ENECO USERNAME>",
          "password": "<ENECO PASSWORD>"
          "consumerKey": "<CONSUMER KEY>",
          "consumerSecret": "<CONSUMER SECRET>"
        }
      ]
    }
```

**Comment by jochem725** [comment]
De consumer key en secret zijn hier te verkrijgen: https://developer.toon.eu

**Comment by RienduPre** [comment]
Hi Jochem,

Eerste indruk.... Werkt perfect.
Bedankt voor je hulp, ondanks het feit dat je geen Toon meer hebt.

Super!

**Comment by bolijndotme** [comment]
Hi Jochem, 

Allereerst bedankt voor het bijwerken van de app! Ik heb zojuist ook de update geïnstalleerd, maar het lijkt hier (nog) niet te werken. Ik heb de consumerKey & -secret, maar weet niet goed wat ik bij 'Callback url' moet invullen. Kun je mij helpen?


<img width="271" alt="schermafbeelding 2019-02-17 om 19 04 23" src="https://user-images.githubusercontent.com/43075336/52917074-58ca5500-32e7-11e9-8e0b-6337c06b041d.png">

**Comment by jochem725** [comment]
@m1ch37 Geen probleem. De plugin gebruikt geen callbacks dus je kunt hier ieder willekeurig IP adres invullen. Zelf heb ik hier `http://127.0.0.1` staan.

**Comment by dannyharuh** [comment]
Hallo @jochem725 jochem725

allereerst bedankt om toch en update te brengen alleen krijg ik dit probleem zou jij hier iets voor weten
ik heb via de terminal van homebridge jou npm geïnstalleerd alleen niet werkend

Mvg Danny van Orsouw

/usr/local/lib/node_modules/homebridge/lib/api.js:122
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
            ^
Error: The requested platform 'Toon' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:122:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:316:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:86:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:45:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)

**Comment by dannyharuh** [comment]
Sorry al gevonden moest eerst de oude plug-in verwijderen en dan de nieuwe installeren het werkt weer super bedankt

**Comment by WimBre** [comment]
Hallo @jochem725 jochem725

Ook namens mij hartelijk dank voor de update.

Homebridge start op maar krijg de navolgende melding:

[2019-2-17 20:20:33] [TOON] Toon Initialized, it may take a few minutes before any data will be visible to HomeKit.
[2019-2-17 20:20:33] Homebridge is running on port 51826.
(node:6942) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'split' of undefined
(node:6942) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code

**Comment by rbeniers** [comment]
Ik kan de plug-in niet installeren.
Als ik de installatie start dan krijg ik de volgende melding: -bash: npm: command not found

Ik installeer de plug-ins veelal via de interface van Homebridge. Kan ik de beta daar ook vinden?

**Comment by jochem725** [comment]
@WimBre Waarschijnlijk heb je een fout gemaakt met het invullen van je inloggegevens of de consumer key / secret.

@rbeniers Ik ben niet bekend met deze interface. Als je geen toegang hebt tot npm via de terminal kun je hem niet eenvoudig installeren.

**Comment by rbeniers** [comment]
Homebridge haalt nu versie 0.0.3 binnen.

Misschien moet je deze hier overschrijven o.i.d.?

Ik zie het nu, Homebridge voert de NPM uit voor de oude versie: npm install -g homebridge-toon
Deze haalt Homebridge iuit Github. Deze zou je dus aan moeten passen naar de nieuwe npm install -g homebridge-toon@beta
Ik kan zelf niets aanpassen in Homebridge

**Comment by WimBre** [comment]
@jochem Bedankt, was idd typefoutje in logingegevens.

**Comment by posttoast** [comment]
Hee, ook hier werkt het weer :) Helemaal fantastisch, duizendmaal dank.

**Comment by gielk** [comment]
Werkt weer !!! Super bedankt. Je bent een helt ! Ben echt blij dat allemaal weer werkt 🙂

**Comment by Dmuiselaar** [comment]
Werkt super!, bedankt voor je snelle actie/hulp! @jochem725

**Comment by jochem725** [comment]
Ik heb geen verdere problemen gevonden en deze versie als latest op npm gezet :)

@rbeniers Je kunt hem nu met versienummer 2.0.4 installeren.

**Comment by rbeniers** [comment]
Dank je wel Jochem, de installatie werkt nu ook via Homebridge!!!!

**Comment by MikeFumbler** [comment]
Te gek Jochem! Dank!
Als onze paden elkaar ooit kruisen, tracteer ik jou op een fles wijn (of andere fijne versnapering).

Kan het overigens zijn dat er een komma mist in de config achter `"<ENECO PASSWORD>"`?
 
```
{
      "platforms": [
        {
          "platform": "Toon",
          "name": "<NAME>",
          "username": "<ENECO USERNAME>",
          "password": "<ENECO PASSWORD>"_(KOMMA HIER ??)_
          "consumerKey": "<CONSUMER KEY>",
          "consumerSecret": "<CONSUMER SECRET>"
        }
      ]
    }
```

Ik kreeg 'm niet door de opstart heen zonder komma, en ook JSON Validator gaf een error.
Na het plaatsen van de komma en het weghalen van de oude Toon accessoire achter "accessories" in de config, werkte het weer!

Een blij man hier.
Dank!

**Comment by gielk** [comment]
Bij mij werkt het even. Maar als nel krijg ik de melding dat mijn keu verlopen is van toon ?

(node:634) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1655): StatusCodeError: 401 - {"fault":{"faultstring":"Access Token expired","detail":{"errorcode":"keymanagement.service.access_token_expired"}}}

Nieuwe aangemaakt. Maar krijg ik weer het zelfde na enkele tijd.

**Comment by bolijndotme** [comment]
Hier inderdaad hetzelfde probleem, @gielk ; na een aantal uur krijg ik de eerder genoemde foutmelding en kan i de Toon niet meer aansturen. Als ik homebridge opnieuw opstart (zonder de config aan te passen!) werkt het wel weer, maar slechts voor een aantal uren. 

Hopelijk is dit ook weer te repareren.

**Comment by jochem725** [comment]
@gielk @m1ch37 Ik heb nog een aantal wijzigingen gedaan die dit op zouden moeten lossen. Kunnen jullie de versie van master installeren? (`npm install -g homebridge-toon`) Het zou opgelost moeten zijn :)

**Comment by posttoast** [comment]
Stomme vraag, maar kan ik gewoon upgraden vanuit de beta naar de master-branch? En zo ja, hoe? Of moet ik eerst de beta uninstallen?

**Comment by bolijndotme** [comment]
> @gielk @m1ch37 Ik heb nog een aantal wijzigingen gedaan die dit op zouden moeten lossen. Kunnen jullie de versie van master installeren? (`npm install -g homebridge-toon`) Het zou opgelost moeten zijn :)

Update geïnstalleerd, dus ik laat je vanmiddag weten of alles nog werkt.  Edit: @jochem725 , bedankt nogmaals voor je snelle (re)actie!

@posttoast , ik heb `npm install -g homebridge-toon` ingegeven. Zo te zien heeft dat de beta overschreven.

**Comment by MikeFumbler** [comment]
Ik las dit op het Toon Forum:

> Koppeling met Domoticz werd nooit officieel ondersteunt door Eneco, Eneco had het ook liever niet aangezien Domoticz in begin de servers behoorlijk belasten(Dit is de reden waarom Domoticz maar 1x in de 5min bijwerkte)..
12 Feb 2019 is officeel de stekker uit http://toonopafstand.eneco.nl/ gehaald, en alle aanhangen mappen. Zo liep ook de koppeling van Domoticz, doordat dat de site helemaal weg is (zelfs de 3 IP adressen zijn niet meer te pingen.), zal de koppeling via Domoticz ook niet snel terugkeren. 
Toon API is geen optie, aangezien je bij x aantal calls of nieuwe API moet aanmaken of moet gaan betalen.

Wat ik er uit haal:
-na een aantal calls via de API (en via de bijbehorende client - en secret code) gaat de API op slot
-je moet dan een nieuwe aanmaken
-of je gaat ervoor betalen
-alle API calls in totaal belastten de Toon/Quby servers te veel -> stekker eruit
-geen meldingen naar geregistreerde Toon gebruikers, gewoon stekker er uit
-Quby (de Toon ontwikkelaars) willen geld zien voor iets wat eerst Open Source was
-Toon heeft nog steeds geen officiële HomeKit koppeling, omdat de servers overbelast werden door gebruikers die toch wegen hiertoe hadden gevonden, trekt men de stekker eruit.

Jammer, heel jammer. En ik vind het met name bezwaarlijk dat ik betaal voor een Eneco Toon op Afstand abonnement, het nog steeds niet officieel kan gebruiken via HomeKit en nu extra moet betalen omdat ik via de prachtige plug-in van Jochem het via HomeBridge toch voor elkaar kreeg.

Of zie ik iets over het hoofd? Is het met de nieuwe versie van Jochem mogelijk om 1x een API registratie aan te maken en die te blijven gebruiken?

**Comment by posttoast** [comment]
Als er inderdaad een limiet is op het aantal calls (in totaal, een limiet op een aantal calls per tijdseenheid kan ik me nog iets bij voorstellen) dan zou dat wel ronduit karig zijn. Dan gaat Toon hier gewoon de deur uit en ga ik naar een thermostaat die native Homekit ondersteunt.

Ik betaal nu ook voor Toon op Afstand, beetje jammer als ik dan enkel die standaard app kan gebruiken.

**Comment by bolijndotme** [comment]
Ik heb vanmorgen om 8uur de nieuwe versie geinstalleerd en alle problemen zijn (tot op heden?) verholpen.

Voordat ik de laatste update installeerde werkte het een aantal uur, waarna ik een foutmelding kreeg en er niets meer mogelijk was. 

Ik ben dus voorzichtig positief dat het (voorlopig?) werkt. Mocht het ineens niet meer werken dan laat ik dat weten.

**Comment by MikeFumbler** [comment]
> Als er inderdaad een limiet is op het aantal calls (in totaal, een limiet op een aantal calls per tijdseenheid kan ik me nog iets bij voorstellen) dan zou dat wel ronduit karig zijn. Dan gaat Toon hier gewoon de deur uit en ga ik naar een thermostaat die native Homekit ondersteunt.
> 
> Ik betaal nu ook voor Toon op Afstand, beetje jammer als ik dan enkel die standaard app kan gebruiken.

Inderdaad. Ik heb op het Toon forum wat reacties achtergelaten en wat opbouwende voorstellen gedaan.

En zo gaat het vaak bij dit soort ontwikkelaars (en zeker gekoppeld aan energie maatschappijen): de aandeelhouders gaan voor.

De Toon app is een van de meest instabiele uit mijn app geschiedenis.
Er is verbetering: een API, vrije keuze om als BETALENDE abonnee (voor Toon alleen, Eneco zelf heb ik er vorig jaar uitgezet) om een andere app te gebruiken voor remote control en geofencing (verwarming uit als je de deur uit loopt, beetje zuinig zijn met gas...). Helaas.
