### ISSUE TITLE
Wijzigingen aan de Toon API? 

### ISSUE THREAD

**Issue by flappah** [jochem725/homebridge-toon#23]
Ik krijg net een email van Eneco dat de Toon API per 1 december veranderd gaat worden. Er is een zgn accesstoken nodig zodat je long lived access krijgt. Dit is specifiek voor de headless applications. Je kunt een accesstoken ophalen op: 

https://api.toon.eu/toonapi-accesstoken?tenant_id=eneco&client_id=<consumer_key>

Inloggen met je Eneco account en je kunt je token ophalen. Hebben jullie plannen om de toon plugin hierop aan te passen?

**Comment by tne7laa** [comment]
I was also curious if someone will update the code for this change. 
Today the [toonapilib](https://github.com/costastf/toonapilib) and [toonapilib4domoticz](https://github.com/JohnvandeVrugt/toonapilib4domoticz) where already updated.

Hope this library will also updated...

**Comment by Hiddecollee** [comment]
Ik wil de toon toevoegen aan HomeBridge, hoe kan ik de key en secret krijgen?

**Comment by Hiddecollee** [comment]
Betekend dit dat de plugin niet meer werkt?

**Comment by flappah** [comment]
Tot nu toe werkt de plugin nog steeds. Maar ik heb geen idee wanneer Eneco de oude authenticatie methodes uitfaseert.

**Comment by MikeFumbler** [comment]
Ik heb de email ook gelezen. Sinds vandaag werkt de HomeBridge Toon plug-in niet meer. 
Allemaal errors over 'UnhandledPromiseRejectionWarning' etc.

Token aangevraagd, zoals vermeld in de email. Dat is gelukt. 
Maar nu: waar in te vullen in de HomeBridge config.json?
Is het token de vervanger van 'ConsumerSecret'? Of dient de Plug-in aangepast te worden om dit te kunnen handelen?

Update: wat gelezen op: [https://developer.toon.eu/authentication](url)

Daar wordt duidelijk dat het een extra laag in de beveiliging is. Client ID en Client secret blijven en zijn nodig om een token te kunnen aanvragen.
In de huidige plug-in is naar mijn idee geen plek om het token in te vullen. Of de plug-in heeft deze functionaliteit nog niet aan board. 

Ik hoop dat Jochem nog zin heeft om dit aan te passen.

**Comment by flappah** [comment]
Ik heb hetzelfde gedaan maar idd, de huidige config biedt geen optie om het token in te vullen. Ik denk dat er idd een aanpassing in de code nodig is. Als ik wat meer tijd heb zal ik eens proberen Jochem z'n code te begrijpen. (en proberen te begrijpen hoe de Eneco api werkt :) )

**Comment by flappah** [comment]
Ik heb zostraks eens even zitten pielen met de Toon API en als ik het goed begrijp vervangt de access token alle andere authenticatie methoden. Met een snelle test met Curl heb ik alleen nog maar dat access token nodig om een agreement-id op te halen. En daarna kan ik met die beide id's de api gaan bevragen. Deze methode zou nu zo in de toon plugin moeten worden uitgewerkt. Overigens werkt de plugin nog steeds bij me thuis. Ik zie dat ik met Homebridge nog steeds waarden van de Toon binnen krijg.

**Comment by MikeFumbler** [comment]
Als ik een temperatuur verandering doorvoer via HomeKit (Eve) en ik volg live de HomeBridge log, zie ik een hele batterij aan meldingen voorbij komen die met het Toon portal te maken hebben, oa. 'UnhandeledPromiseRejectionWarning'. Toon zelf reageert niet op de wijziging.

De Toon app zelf werkt wel. In de log zie ik ook de polls, daar vind ik: 'Current Temperatuur: undefined'.

Het lijkt erop dat de plug-in inderdaad geen data of reactie krijgt van de Quby servers.

**Comment by flappah** [comment]
Hmm .. ik ben al eens begonnen met de code te bekijken om te zien wat er nu aangepast moet worden. Uit m'm experimenten gisteren (met curl) leek het erop dat er een aantal zaken uit de config file vervangen kunnen worden door dat nieuwe permanent access token.

**Comment by Hiddecollee** [comment]
Al meer over bekend?

**Comment by Hiddecollee** [comment]
> Hmm .. ik ben al eens begonnen met de code te bekijken om te zien wat er nu aangepast moet worden. Uit m'm experimenten gisteren (met curl) leek het erop dat er een aantal zaken uit de config file vervangen kunnen worden door dat nieuwe permanent access token.

Even off topic: Heb jij nu met de huidige plugin de volgende mogelijkheden:  uit, opwarmen of automatisch?

**Comment by flappah** [comment]
> Al meer over bekend?

Het is wat op de achtergrond geraakt omdat ik een release had op t werk wat m’n aandacht wat vasthield dus nee, ik heb niet meer verder naar de code gekeken. Sorry. 

> Even off topic: Heb jij nu met de huidige plugin de volgende mogelijkheden: uit, opwarmen of automatisch?

Yep. Bij mij werkt alles nog op de raspberry pi. Heb homebridge nog recentelijk geactualiseerd en de toon plug-in gaat nog steeds goed. Ik kan de temperatuur nog steeds gewoon aanpassen vanuit de Home app op de iPhone.

**Comment by Hiddecollee** [comment]
> Yep. Bij mij werkt alles nog op de raspberry pi. Heb homebridge nog recentelijk geactualiseerd en de toon plug-in gaat nog steeds goed. Ik kan de temperatuur nog steeds gewoon aanpassen vanuit de Home app op de iPhone.

Dus je kan instellen dat de toon uit staat, verwarmd of automatisch de warmte regelt?

**Comment by flappah** [comment]
> > Yep. Bij mij werkt alles nog op de raspberry pi. Heb homebridge nog recentelijk geactualiseerd en de toon plug-in gaat nog steeds goed. Ik kan de temperatuur nog steeds gewoon aanpassen vanuit de Home app op de iPhone.
> 
> Dus je kan instellen dat de toon uit staat, verwarmd of automatisch de warmte regelt?

Yep. Met een HomeKit automation kan ik dat doen. Bij thuiskomst start ie en bij weggaan gaat ie uit. En bij welterusten gaat ie ook uit.

**Comment by Hiddecollee** [comment]
@flappah Jij hebt dus hier de modus staan?
![9E53DD04-4CFF-466E-8D58-0A7300CCE534](https://user-images.githubusercontent.com/29307825/71604285-4f458680-2b61-11ea-8424-d8fdfbb180be.jpeg)

**Comment by flappah** [comment]
Hmm. Nee. Dat niet. 
![FD0D845E-EEE8-4DE1-8012-17C01F3C02F2](https://user-images.githubusercontent.com/14106566/71617175-374e2100-2bba-11ea-8229-e8b4755fb2f7.png)

**Comment by Mikevdkooij** [comment]
Goedenavond, 

Ik heb Toon werkend gekregen binnen HomeBridge (HOOBS). Ik heb alleen een probleempje en vraag me af of iemand hier ervaring mee heeft.

Ik kan via HomeBridge de temperatuur aanpassen van de thermostaat, dit gaat allemaal prima. Ik krijg de accessoire alleen niet te zien in HomeKit. Iemand een idee?

**Comment by flappah** [comment]
Ik snap je vraag niet helemaal. Je opent Home op je iPhone, drukt op "+" (naast Edit), selecteert "Add Accessory" en scant de code (of voert m handmatig in) en dan verschijnt alles wat je in HomeBridge hebt aangemeld in Home. Meer is het niet.

**Comment by Mikevdkooij** [comment]
> Ik snap je vraag niet helemaal. Je opent Home op je iPhone, drukt op "+" (naast Edit), selecteert "Add Accessory" en scant de code (of voert m handmatig in) en dan verschijnt alles wat je in HomeBridge hebt aangemeld in Home. Meer is het niet.

Klopt helemaal. Zo simpel zou het moeten zijn, echter de Toon Plug-in komt niet tevoorschijn tussen de accessoires. De rest van de plug-ins wel, zoals: Samsung TV, Hue, Xiaomi lichten etc.

Ik heb wel een geldige naam ingevuld, wachtwoord, consumer secret etc. Via HomeBridge via het web zie ik hem wel.

**Comment by flappah** [comment]
> Klopt helemaal. Zo simpel zou het moeten zijn, echter de Toon Plug-in komt niet tevoorschijn tussen de accessoires. De rest van de plug-ins wel, zoals: Samsung TV, Hue, Xiaomi lichten etc.
> 
> Ik heb wel een geldige naam ingevuld, wachtwoord, consumer secret etc. Via HomeBridge via het web zie ik hem wel.

Vreemd. Bij mij staat ie er gewoon tussen. Ik heb overigens alleen de Toon en het Netatmo weerstation via HomeBridge lopen. De rest loopt via hun eigen bridges (Aqara en Hue). Voor de rest heb ik nog wat Eve Elgato spullen en een aantal Koogeek stekkerdozen. Die zitten rechtstreeks aan HomeKit. Hier heb ik geen problemen mee.

**Comment by tne7laa** [comment]
Weet niet of je hetzelfde homebridge config gebruik maar ik moet in domoticz onder Instellingen-Meer Opties- Ruimtes- Kamerplan de apparaten onder een regel die Homebridge heet toevoegen. Daarna zie ik ze pas on homebridge.

**Comment by ruudbol** [comment]
Bij mij werkt de plugin ook niet meer sinds vandaag,
Is er al wat meer bekend of de plugin aangepast kan worden.

**Comment by ruudbol** [comment]
> > Al meer over bekend?
> 
> Het is wat op de achtergrond geraakt omdat ik een release had op t werk wat m’n aandacht wat vasthield dus nee, ik heb niet meer verder naar de code gekeken. Sorry.
> 
> > Even off topic: Heb jij nu met de huidige plugin de volgende mogelijkheden: uit, opwarmen of automatisch?
> 
> Yep. Bij mij werkt alles nog op de raspberry pi. Heb homebridge nog recentelijk geactualiseerd en de toon plug-in gaat nog steeds goed. Ik kan de temperatuur nog steeds gewoon aanpassen vanuit de Home app op de iPhone.

Hoi,  is er al een oplossing voor handen ? Bij mij werkt de plugin inmiddels ook niet meer

**Comment by flappah** [comment]
Sinds vandaag lijkt de boel ook hier niet meer te werken. Er wordt een lading exceptions gegenereerd. Maar tegelijkertijd zie ik dat de Toon app ook niet werkt. Geen idee of Jochem tijd heeft om de plugin weer eens bij te werken?

**Comment by flappah** [comment]
> 
> Hoi, is er al een oplossing voor handen ? Bij mij werkt de plugin inmiddels ook niet meer

Het lijkt erop dat Jochem dit project verlaten heeft. Ik ga maar eens proberen of ik er iets van kan maken. Kan wel even duren want ik ben pas over twee weken weer in NL maar wanneer ik weer thuis ben dan zal ik eens zien wat ik er van kan maken.

**Comment by jochem725** [comment]
Hoi allen,

Zelf gebruik ik deze plugin niet meer (en heb ik de mail van Eneco/Github issues niet ontvangen 🙈). 
Het probleem zou opgelost moeten zijn in de nieuwste versie op NPM. 

De config file moet aangepast worden met het nieuwe 10 jaar geldige API Token wat hier verkrijgbaar is: `https://api.toon.eu/toonapi-accesstoken?tenant_id=eneco&client_id=<consumer_key>`

https://github.com/jochem725/homebridge-toon/tree/fix-apitoken

Zelf kan ik deze changes nu niet testen, dus ik ben benieuwd naar jullie ervaringen 😄

**Comment by ruudbol** [comment]
> Hoi allen,
> 
> Zelf gebruik ik deze plugin niet meer (en heb ik de mail van Eneco/Github issues niet ontvangen 🙈).
> Het probleem zou opgelost moeten zijn in de nieuwste versie op NPM.
> 
> De config file moet aangepast worden met het nieuwe 10 jaar geldige API Token wat hier verkrijgbaar is: `https://api.toon.eu/toonapi-accesstoken?tenant_id=eneco&client_id=<consumer_key>`
> 
> https://github.com/jochem725/homebridge-toon/tree/fix-apitoken
> 
> Zelf kan ik deze changes nu niet testen, dus ik ben benieuwd naar jullie ervaringen 😄

Hoi Jochem, ontzettend bedankt voor het aanpassen van de plugin, hij werkt nu weer perfect.

**Comment by flappah** [comment]
> Hoi allen,
> 
> Zelf gebruik ik deze plugin niet meer (en heb ik de mail van Eneco/Github issues niet ontvangen 🙈).
> Het probleem zou opgelost moeten zijn in de nieuwste versie op NPM.
> 
> De config file moet aangepast worden met het nieuwe 10 jaar geldige API Token wat hier verkrijgbaar is: `https://api.toon.eu/toonapi-accesstoken?tenant_id=eneco&client_id=<consumer_key>`
> 
> https://github.com/jochem725/homebridge-toon/tree/fix-apitoken
> 
> Zelf kan ik deze changes nu niet testen, dus ik ben benieuwd naar jullie ervaringen 😄

Ha Jochem, 

kon de update nog net toepassen voordat ik weg moet en alles lijkt te werken! Top man! Ben wel benieuwd wat je nu eigenlijk gedaan hebt. Zal de code eens door gaan scannen na m'n trip! Tnx!

**Comment by Hiddecollee** [comment]
> > Hoi allen,
> > Zelf gebruik ik deze plugin niet meer (en heb ik de mail van Eneco/Github issues niet ontvangen 🙈).
> > Het probleem zou opgelost moeten zijn in de nieuwste versie op NPM.
> > De config file moet aangepast worden met het nieuwe 10 jaar geldige API Token wat hier verkrijgbaar is: `https://api.toon.eu/toonapi-accesstoken?tenant_id=eneco&client_id=<consumer_key>`
> > https://github.com/jochem725/homebridge-toon/tree/fix-apitoken
> > Zelf kan ik deze changes nu niet testen, dus ik ben benieuwd naar jullie ervaringen 😄
> 
> Ha Jochem,
> 
> kon de update nog net toepassen voordat ik weg moet en alles lijkt te werken! Top man! Ben wel benieuwd wat je nu eigenlijk gedaan hebt. Zal de code eens door gaan scannen na m'n trip! Tnx!

Hoe werkt het precies met die API token, etc? Voor de update werkte nog alles maar nu niet meer... Ik heb een consumer key en secret maar verder snap ik het niet...
