### ISSUE TITLE
Werking van de Toon in HomeKit

### ISSUE THREAD

**Issue by Hiddecollee** [jochem725/homebridge-toon#24]
Hoi, de plug-in werkt goed. Toch twijfel ik of het nu helemaal goed is.. Ik heb namelijk geen instelling om de modus te veranderen (uit, verwarmen en automatisch).. Klopt dit?

Ook staat er altijd "Automatisch is 19,0 C" ook wanneer de temperatuur al 19,0 C is..
![IMG_0552](https://user-images.githubusercontent.com/29307825/70807206-59276580-1dbd-11ea-8746-88bbe509ee86.jpeg)

`
"platforms": [
        {
            "platform": "Toon",
            "name": "Thermostaat",
            "username": "x",
            "password": "x",
            "consumerKey": "x",
            "consumerSecret": "x"
        }
    ]
`

**Comment by Hiddecollee** [comment]
Is er iemand die mij hier mee kan helpen? ik zou graag willen instellen of de toon uit moet staan of verwarmen..

**Comment by gielk** [comment]
Ik had ook al een keer aangegeven dan gebruik te maken van de 4 standen die we hebben in toon slapen weg thuis of comfort. Maar begreep dat de ontwikkelaar toon zelf niet meer gebruikt.

**Comment by bolijndotme** [comment]
Voorheen was die mogelijkheid er wel. Als je klikte op de toon-tegel dan kreeg je een popup waarmee je de temperatuur in kon stellen. Er stond dan ook een tandwiel bij, waarmee je een menu opende waarin je kon kiezen tussen verwarmen, uit, automatisch en koelen. 

Die functionaliteit is er nu niet meer, maar ik weet niet zeker of het door deze plugin komt of doordat dit in Homekit anders werkt. De functionaliteit om de temperatuur in te stellen is nu ook anders weergegeven. 

Ik heb wel ergens bij een update in de code gezien dat de modus altijd op verwarmen staat, omdat Toon alleen kan verwarmen en niet kan koelen. 

Edit:
Zie hier het stuk code wat ik bedoel:
https://github.com/jochem725/homebridge-toon/blob/e45db9fa5c1c2aaf8431da516d5516e95d2eaeb0/src/index.ts#L134

Hoop dat het je helpt!

**Comment by Hiddecollee** [comment]
Hey @m1ch37 

Ik heb ook een Tado thermostaat knop in HomeKit en daar heb ik ook een menu waarin je kan kiezen tussen verwarmen, uit, en automatisch. 

Het zou dus ook mogelijk moeten zijn voor deze plug-in...

**Comment by Peet-B** [comment]
Ik heb een (weliswaar niet geweldige) oplossing gevonden. Ik heb via Olisto mijn Toon-account gekoppeld, en daarna de homebridge-olisto toegevoegd. Je kunt via Olisto "connectors" toevoegen, en via de app vervolgens toevoegen wat er gebeurt nadat de "connector" is geactiveerd, zo heb ik dus 4 verschillende connectors, die ieder voor een aparte scene van Toon staan.
