### ISSUE TITLE
Werkt deze plugin nog?

### ISSUE THREAD

**Issue by sjaccoo2001** [jochem725/homebridge-toon#32]
Hallo,

Ik vroeg me af of deze plugin nog werkt, ik ben al 3 dagen aan het proberen om het werkend te krijgen, maar dit lukt me niet. Ik hoop dat ik zelf een foutje heb ingevuld en dat iemand mij kan helpen. Ik zou het namelijk erg jammer vinden als deze plugin niet meer zou werken. Ik krijg de volgende melding van homebridge. Hieronder vinden jullie ook mijn config.

[10/6/2020, 19:14:28] [Toon] Current Temperature:  undefined
[10/6/2020, 19:14:28] [Toon] Current Target Temperature:  undefined

        {
            "platform": "Toon",
            "name": "Toon",
            "username": "x",
            "password": ''x",
            "consumerKey": "x",
            "consumerSecret": "x"
        }
    ]
}

**Comment by wtrdk** [comment]
Bij mij werkt hij prima. Hij geeft wel wat foutmeldingen in de logs, maar alles werkt. Mijn config:

```
{
            "platform": "Toon",
            "name": "Toon",
            "apiToken": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX",
            "agreementIndex": "0"
        }
```

**Comment by sjaccoo2001** [comment]
Zou je mij uit kunnen leggen hoe ik aan een API token kom? Ik kom er maar niet uit...

**Comment by wtrdk** [comment]
Natuurlijk!
Je moet inloggen (of eerst een account aanmaken) op https://developer.toon.eu/
Daar maak je via 'add a new app' een nieuw app aan, die noem je bijvoorbeeld Homebridge.
Dan krijg je de benodigde gegevens. Succes!

**Comment by sjaccoo2001** [comment]
Ik ben er al uit gekomen, ik zag de api token over het hoofd. In een eerdere versie kon je gewoon de consumer secret en key toevoegen. Maar ben er achter gekomen hoe ik de api token moest aanvragen. De plug-in werkt nu super! Als nog bedankt voor je hulp!

**Comment by SuHwak** [comment]
> Ik ben er al uit gekomen, ik zag de api token over het hoofd. In een eerdere versie kon je gewoon de consumer secret en key toevoegen. Maar ben er achter gekomen hoe ik de api token moest aanvragen. De plug-in werkt nu super! Als nog bedankt voor je hulp!

Zou je mij en anderen ook kunnen helpen door uit te leggen hoe je de API token aanvraagt? Want ik heb op https://developer.toon.eu/authentication gekeken, maar daar kom ik niet uit.

**Comment by SuHwak** [comment]
Ah, eindelijk toch gevonden. (de eerste paar stappen had ik al gedaan)
1. Op https://developer.toon.eu registreren
2. Creeer een nieuwe app op https://developer.toon.eu/user/me/apps
3. Voor de callback url hoef je geen werkende url in te vullen, http://localhost.com of iets dergelijks moet ook werken.
4. Nu heb je voor je nieuwe app een consumer key en Id gekregen.
5. Gebruik je eigen consumer_key in deze url in je browser:
6. https://api.toon.eu/toonapi-accesstoken?tenant_id=eneco&client_id=<consumer_key>
7. Login met je Mijn Eneco inlog gegevens
8. Sla de Api Token die je nu ziet ergens goed en veilig op (bv in je password manager)
9. Ga naar je config van HomeBridge en voeg het volgende toe (zie voorbeeld plaatje): 
`            "platform": "Toon",`
`            "name": "Toon",`
`            "apiToken": "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"`
Zoals dit:
![Screenshot 2020-12-26 120251](https://user-images.githubusercontent.com/3165441/103150236-6d44c780-4772-11eb-9f7a-55efac314512.jpg)
10. Vergeet de comma niet op lijn 14
11. Herstart HomeBridge, en vervolgens zou het moeten werken:


`[12/26/2020, 11:59:49 AM] [Toon] Initializing Toon platform...`
`[12/26/2020, 11:59:49 AM] [Toon] Getting agreement...`
`[12/26/2020, 11:59:49 AM] [Toon] Toon Initialized, it may take a few minutes before any data will be visible to HomeKit.`

`[12/26/2020, 11:59:49 AM] [Toon] Currently selected agreementIndex: 0`
`[12/26/2020, 11:59:57 AM] [Toon] Current Temperature:  undefined`
`[12/26/2020, 11:59:57 AM] [Toon] Current Target Temperature:  undefined`
`[12/26/2020, 12:00:01 PM] [Toon] Current Temperature:  undefined`
`[12/26/2020, 12:00:01 PM] [Toon] Current Target Temperature:  undefined`
`[12/26/2020, 12:07:22 PM] [Toon] Current Temperature:  19.5`
`[12/26/2020, 12:07:22 PM] [Toon] Current Target Temperature:  19.5`
`[12/26/2020, 12:07:25 PM] [Toon] Current Temperature:  19.5`
`[12/26/2020, 12:07:25 PM] [Toon] Current Target Temperature:  19.5`

**Comment by sjaccoo2001** [comment]
Gelukkig heb je t gevonden!
Ik vond het zelf ook best verwarrend ik vulde steeds de key in die ik kreeg vanuit eneco. Na 100 keer lezen zag ik dat linkje en toen dacht ik aha...
