### ISSUE TITLE
Inloggen lukt niet

### ISSUE THREAD

**Issue by gielk** [jochem725/homebridge-toon#5]
Hi ik krijg een foutmelding heb wel de juiste gegevens in gevuld zo ver ik weet.
Ik gebruik gewoon e-mail en wachtwoord die ik ook gebruik om in te loggen op de website en de app.

Heb ook geen idee wat ik moet invullen bij naam
 
kun je mij helpen ??

![config file](https://cloud.githubusercontent.com/assets/24224715/20667869/de613d4c-b56b-11e6-8ef2-10a59602d631.png)

![foutmelding](https://cloud.githubusercontent.com/assets/24224715/20667829/b2a13180-b56b-11e6-8094-8caff6cf4065.png)

**Comment by jochem725** [comment]
Hoi @gielk, dit lijkt me een probleem met de `config.json` file van Homebridge. Volgens mij is het gedeelte onder `"bridge":` ongeldig. Zie hier een voorbeeld van een geldige configfile: https://github.com/nfarina/homebridge/blob/master/config-sample.json

**Comment by gielk** [comment]
Sorry verkeerde screenshot. Dit is de goeie

https://goo.gl/photos/kTMg42vMhVjU3S1M7

**Comment by jochem725** [comment]
@gielk Als ik dat zo zie lijkt het me toch dat je inloggegevens onjuist zijn. Kun je even checken of je hier in kunt loggen? https://toonopafstand.eneco.nl/. Als je daar in kunt loggen, zou het ook via Homebridge moeten werken.

**Comment by gielk** [comment]
Ja ik kan daar wel inloggen met deze gegevens.

**Comment by gielk** [comment]
Oei oei schaam mij diep. Bedankt voor de herinnering. Zie dat in dubbele " heb laten staan ! Bedankt voor je snelle reacties !!!! Super blij.

**Comment by jochem725** [comment]
@gielk Top! Graag gedaan 😄
