### ISSUE TITLE
Error: There was an error authenticating with Toon

### ISSUE THREAD

**Issue by hogendoorn** [jochem725/homebridge-toon#8]
Ik krijg het niet voor elkaar om verbinding te maken met de Toon. Ik las in vorige posts dat als je kan inloggen op https://toonopafstand.eneco.nl/index_pc.html het zou moeten werken. Maar helaas lukt het me niet. 

Dit is de config die ik gebruik: 
{
        "bridge": {
                "name": "Homebridge",
                "username": "CC:22:3D:E3:CE:30",
                "port": 41947,
                "pin": "031-45-154"
        },

        "accessories": [{
                "accessory": "Toon",
                "name": "Toon",
                "username": "a@ziggo.nl",
                "password": "Wachtwoord"
        }]
}

Nu viel me op dat wanneer ik inlog op de site ik moest keuze voor een adres. ik ben een keer verhuist. Nu heb ik 1 addres als default gekozen zodat ik de vraag niet meer krijg. Zou dit er iets mee te maken kunnen hebben ?

**Comment by jochem725** [comment]
@flippamike Dit zou heel goed kunnen. De plugin pakt nu het eerste adres uit de lijst met `agreements` die de volgende API call teruggeeft: https://toonopafstand.eneco.nl/toonMobileBackendWeb/client/login?username=USERNAME&password=PASSWORD

Kun je me laten weten of je huidige adres de eerste of de tweede entry in `agreements` is? Ik neem hierbij aan dat de output van de plugin een credentials error geeft.

**Comment by hogendoorn** [comment]
He @jochem725, bedankt voor je snelle reactie. Hij is helaas de eerste. Is dit aan te passen?

**Comment by jochem725** [comment]
@flippamike Hmm, als het de eerste in de lijst is zou je andere adres niet het probleem moeten zijn, omdat hij altijd de entry pakt die als eerste in de lijst is vermeld pakt hij nu dus ook het juiste adres.

Om uit te sluiten dat het toch niet in de config zit, zou je je config door http://jsonlint.com willen halen om te zien of deze correct is?

**Comment by hogendoorn** [comment]
@jochem725 ik heb het inmiddels verholpen. Ik zag dat je in toon.js naar agreements[0] kijkt. ik heb hem aangepast naar agreements[1] en dit werkt perfect! 

Offtopic: Maak je toevallig ook verbinding naar een Philips Hue ?

**Comment by jochem725** [comment]
@flippamike Ah dus toch. Mooi dat het werkt. Ik zal een config optie aanmaken om een agreement te selecteren zodat je de code niet hoeft te wijzigen. 

Ik ben aan het kijken of de smart plugs die met de Toon bediend kunnen worden geïntegreerd kunnen worden in deze plugin. Als het goed is ondersteunen de nieuwere Hue bridges HomeKit standaard. Voor de oudere bridges zou er een andere Homebridge plugin moeten zijn.

**Comment by hogendoorn** [comment]
Leuk, laat maar weten als dat is gelukt! Dit plugin daar ben ik mee bezig maar hij stopt zonder fout melding erg vreemd..

**Comment by hogendoorn** [comment]
Nog 1 vraag, Klopt het dat ik hem niet kan automatiseren vanuit de app?

**Comment by jochem725** [comment]
@flippamike Dat zou gewoon moeten werken. Als je de temperatuur instelt gaat dit goed, de opties `Koelen`, `Verwarmen` etc. doen niets omdat Toon alleen werkt op basis van temperatuur (verwarming aan/uit).

**Comment by jochem725** [comment]
@flippamike Ik heb het selecteren van een agreement geïmplementeerd in #10. Zou je dit een kunnen proberen?
